version: "3.9"

services:
  telegram_app:
    build:
      context: .
      dockerfile: "Dockerfile"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    container_name: telegram_app
    env_file:
      - .env